#ifndef _DPFILTER_H
#define _DPFILTER_H

#define DPFLTR_ERROR_LEVEL 0
#define DPFLTR_WARNING_LEVEL 1
#define DPFLTR_TRACE_LEVEL 2
#define DPFLTR_INFO_LEVEL 3

typedef enum _DPFLTR_TYPE {
	DPFLTR_SYSTEM_ID = 0,
	DPFLTR_ACPI_ID = 24,
	DPFLTR_PCI_ID = 66,
	DPFLTR_IHVDRIVER_ID = 77,
	DPFLTR_IHVVIDEO_ID = 78,
	DPFLTR_IHVAUDIO_ID = 79,
	DPFLTR_IHVNETWORK_ID = 80,
	DPFLTR_IHVSTREAMING_ID = 81,
	DPFLTR_IHVBUS_ID = 82,
	DPFLTR_NDIS_ID = 120
} DPFLTR_TYPE;

#endif
